CREATE DATABASE UNIFRANZITOS_1
USE UNIFRANZITOS_1;

CREATE TABLE CAMPEONATO(
id_CAMP VARCHAR(50) PRIMARY KEY NOT NULL,
NOMBRE_CAMPEONATO VARCHAR(50) NOT NULL,
SEDE VARCHAR(50) NOT NULL
);

INSERT INTO CAMPEONATO (id_CAMP,NOMBRE_CAMPEONATO,SEDE)
VALUES('camp-111','Campeonato Unifranz','El Alto'),('camp-222','Campeonato Unifranz','Cochabamba');

CREATE TABLE EQUIPO(
ID_EQUI VARCHAR(50)PRIMARY KEY NOT NULL,
NOMBRE_EQUIPO VARCHAR(50) NOT NULL,
CATEGORIA VARCHAR(50) NOT NULL,
id_CAMP VARCHAR(50) NOT NULL,
FOREIGN KEY (id_CAMP) REFERENCES CAMPEONATO (id_CAMP),
);

INSERT INTO EQUIPO(ID_EQUI,NOMBRE_EQUIPO,CATEGORIA,id_CAMP)
VALUES('equ-111','Google','varones','camp-111'),('equ-222','404 Not found','varones','camp-111'),
('equ-333','girls unifranz','mujeres','camp-111');

CREATE TABLE JUGADOR(
id_JUG VARCHAR(50) PRIMARY KEY NOT NULL,
NOMBRES VARCHAR(50) not null,
APELLIDOS VARCHAR(50) not null,
CI   varchar(50) not null,
EDAD INTEGER not null,
ID_EQUI VARCHAR(50) not null,
FOREIGN KEY (ID_EQUI) REFERENCES EQUIPO (ID_EQUI)
);

INSERT INTO JUGADOR (id_JUG,NOMBRES,APELLIDOS,CI,EDAD,ID_EQUI)
VALUES('jug-111','Carlos','Villa','8997811LP',19,'equ-222'),
('jug-222','Pedro','Salas','8997822LP',20,'equ-222'),
('jug-333','Saul','Araj','8997833LP',21,'equ-222'),
('jug-444','Sandra','Solis','8997844LP',20,'equ-333'),
('jug-555','Ana','Mica','8997855LP',23,'equ-333');

SELECT * FROM CAMPEONATO;
SELECT * FROM EQUIPO;
SELECT * FROM JUGADOR;

SELECT COUNT(*) JUGADORES_QUE_FORMAN_EL_EQUIPO_333
FROM JUGADOR AS JUG 
INNER JOIN EQUIPO AS EQUI ON JUG.ID_EQUI = EQUI.ID_EQUI
WHERE EQUI.ID_EQUI = 'EQU-333';

SELECT COUNT(*) CUANTOS_JUGADORES_SON
FROM JUGADOR AS JUG
INNER JOIN CAMPEONATO AS CAMP ON JUG.ID_EQUI = CAMP.id_CAMP
WHERE CAMP.NOMBRE_CAMPEONATO = 'Campeonato Unifranz';

	DROP FUNCTION F1_CANTIDAD_DE_JUGADORES;

CREATE FUNCTION F1_CANTIDAD_DE_JUGADORES(@sede VARCHAR (25))
RETURNS VARCHAR (25) AS 
BEGIN
		DECLARE @RESPONSE VARCHAR (25);
		SELECT @RESPONSE = COUNT(id_JUG)
		FROM JUGADOR AS JUG
		INNER JOIN CAMPEONATO AS CAMP ON CAMP.id_CAMP = JUG.id_JUG
		WHERE CAMP.SEDE = 'El Alto';


RETURN @RESPONSE;
END;
SELECT dbo.F1_CANTIDAD_DE_JUGADORES('El Alto') cuantos_jugadores

SELECT count (id_JUG)
FROM JUGADOR AS JUG
INNER JOIN EQUIPO AS EQUI ON JUG.ID_EQUI = EQUI.ID_EQUI
WHERE EQUI.NOMBRE_EQUIPO = 'girls unifranz' AND EQUI.CATEGORIA = 'mujeres';

CREATE FUNCTION F2_CANTIDAD_JUGADORES_PAM(@NOMBRE_EQUIPO VARCHAR (25),@CATEGORIA VARCHAR(25))
RETURNS VARCHAR (25) AS
BEGIN  
		DECLARE @RESPUESTA VARCHAR (25);
		SELECT @RESPUESTA = count (id_JUG)
		FROM JUGADOR AS JUG
		INNER JOIN EQUIPO AS EQUI ON JUG.ID_EQUI = EQUI.ID_EQUI
		WHERE EQUI.NOMBRE_EQUIPO = 'girls unifranz' AND EQUI.CATEGORIA = 'mujeres';
		RETURN @RESPUESTA;
END;
DROP FUNCTION F2_CANTIDAD_JUGADORES_PAM;
SELECT dbo.F2_CANTIDAD_JUGADORES_PAM('grils inufranz','mujeres');

select COUNT (id_JUG)
from JUGADOR as JUG
INNER JOIN EQUIPO AS EQUI ON JUG.ID_EQUI = EQUI.ID_EQUI
where JUG.edad > 21 AND EQUI.CATEGORIA = 'mujeres';

CREATE FUNCTION F3_PROMEDIO_EDAD(@EDAD INT,@CATEGORIA VARCHAR(25))
RETURNS INT AS 
BEGIN 
		DECLARE @RESPUESTA INT = 0;
		select @RESPUESTA = COUNT (id_JUG)
		from JUGADOR as JUG
		INNER JOIN EQUIPO AS EQUI ON JUG.ID_EQUI = EQUI.ID_EQUI
		where JUG.edad > 21 AND EQUI.CATEGORIA = 'mujeres';
		RETURN @RESPUESTA;
	END;
SELECT dbo.F3_PROMEDIO_EDAD(21,'mujeres');

SELECT COUNT (id_JUG)
from JUGADOR AS JUG
INNER JOIN EQUIPO AS EQUI ON JUG.ID_EQUI = EQUI.ID_EQUI
INNER JOIN CAMPEONATO AS CAMP ON CAMP.id_CAMP = EQUI.ID_EQUI
WHERE EQUI.NOMBRE_EQUIPO = '404 Not found' or CAMP.SEDE = 'El Alto' and JUG.NOMBRES = 'Carlos';

CREATE FUNCTION F4_CONCATLTEMS(@nombres varchar (25),@sede varchar (25),@nombre_equipo varchar(25))
RETURNS VARCHAR (25) AS
BEGIN 
		DECLARE @RESPUESTA VARCHAR(25);
		SELECT @RESPUESTA = COUNT (id_JUG)
		from JUGADOR AS JUG
		INNER JOIN EQUIPO AS EQUI ON JUG.ID_EQUI = EQUI.ID_EQUI
		INNER JOIN CAMPEONATO AS CAMP ON CAMP.id_CAMP = EQUI.ID_EQUI
		WHERE EQUI.NOMBRE_EQUIPO = '404 Not found' or CAMP.SEDE = 'El Alto' and JUG.NOMBRES = 'Carlos';
		RETURN @RESPUESTA;
	END;
SELECT dbo.fibonacci(5);


